### ISSUE TITLE
The chat font and users' names are both white, making it hard to read on some games.

### ISSUE THREAD

**Issue by venfabio** [Enubia/ghost-chat#144]
I'm having an hard time reading the chat because users' names and their messages are both white. It would be very helpful to:

A) Have a different colour for each user.
B) Have a black border on the font.
C) Choose different chat colour and border colour.

Is it something feasible?

I'm loving this lightweight application, but this only issue is giving me a very hard time!

Thanks for the hard work.

**Comment by Enubia** [comment]
User name colors are determined by their corresponding twitch color which is parsed from the twitch api. But I already noticed that sometimes user names are just plain white which I understand makes it hard to read in some situations. I will take a look at that.

https://github.com/Enubia/ghost-chat/issues/148
