### ISSUE TITLE
Messages Order

### ISSUE THREAD

**Issue by chescalante** [Enubia/ghost-chat#166]
Hi, is there a way (I don't see it in the settings) to show the new message from above instead of appearing at the end?

**Comment by Enubia** [comment]
Hey, currently not but I can look at it for the next release.

**Comment by chescalante** [comment]
Perfect, thank you, let me know if I could help.

**Comment by Enubia** [comment]
resolved with #203

**Comment by Enubia** [comment]
@chescalante i will create the next release later on this week since I want to implement the BTTV and FFZ emote support for this as well!
