### ISSUE TITLE
Chat doesn't scroll properly.

### ISSUE THREAD

**Issue by venfabio** [Enubia/ghost-chat#196]
Hi!

I'm using Ghost Chat in every stream, and I noticed the chat doesn't scroll properly. When the window is over, instead of scrolling for new messages it just ignores them. So I have to restart it everytime.

**Comment by Enubia** [comment]
What do you mean by "the window is over"? If the chat is in background behind the application you want to overlay it?

**Comment by venfabio** [comment]
I mean the size of the window.  If I adjust the size to fit 7 messages, the 8th will not be displayed because the chat should scroll, but it doesn't.

**Comment by fabianvf** [comment]
I have also seen this, once enough messages pop up I need to restart it

**Comment by rylenk** [comment]
I have also seen chat not scroll properly, only when click through is enabled (the ghost button), and reverse chat not selected (so the newest messages appear on the bottom). Once the messages get to the bottom of the ghost chat window, they disappear and the chat does not scroll with the new messages. The removal of messages in minutes is also set to 0.
I have not seen issues with this when click through is not enabled.

**Comment by FoxKeegan** [comment]
Confirming what Rylenk has stated above. I can replicate all of this. Thanks for pointing out that reverse chat is a workaround

**Comment by Enubia** [comment]
Seems like there's a problem with the window scrollTop once the app is in click through mode, will have a look at it on the weekend. 👍 for now please use reverse chat mode as a workaround

**Comment by Enubia** [comment]
i've gone ahead and enabled the reverted scrolling as default for now which is also not changeable unfortunately

there's something weird going on with the frameless window and scrolling behaviour

i will try to fix this in the next few days so that it's working properly again
