### ISSUE TITLE
Founders Badges

### ISSUE THREAD

**Issue by rylenk** [Enubia/ghost-chat#248]
**Is your feature request related to a problem? Please describe.**
I've noticed people with Founders Badges don't show up with a subscriber badge (the star) or a Founders Badge (the pink 1st badge on Twitch) in Ghost Chat. Right now in Ghost Chat, people with a Founders Badge appear to not be a subscriber at all.

**Describe the solution you'd like**
Show the Founders Badge in Ghost Chat next to the viewer's name, like in Twitch chat.

**Describe alternatives you've considered**
Replacing the Founders Badge with a channel subscriber badge, but that seems more difficult since it doesn't appear that way on Twitch, so this may not be a viable option.

**Additional context**
Example of the same message, Twitch chat on the left with the Founders Badge, and Ghost Chat on the right missing the Founders Badge (name removed for privacy).
![Founders Badge](https://user-images.githubusercontent.com/73735624/97774179-fa70f480-1b12-11eb-8cb0-955b670a1b31.png)

**Comment by Enubia** [comment]
looking into this issue in the next couple of days

**Comment by Enubia** [comment]
https://github.com/Enubia/ghost-chat/releases/tag/v2.0.0
