### ISSUE TITLE
BTTV Emotes

### ISSUE THREAD

**Issue by cherrypibb** [Enubia/ghost-chat#288]
**Is your feature request related to a problem? Please describe.**
My chat uses a lot of BTTV emotes and it would be nice to see the emotes instead of the text for them.

**Describe the solution you'd like**
Be able to see BTTV emotes in ghost chat

**Comment by sp96296** [comment]
Bump, bttv and ffz emotes would be lovely.

**Comment by Enubia** [comment]
I will be looking into BTTV emotes during the next couple of days. FFZ will be harder tho since they still don't provide an official documentation on how to obtain/parse them.

**Comment by djfrailey** [comment]
@Enubia I haven't had time to test it however this seems like it would do what you need it to do: https://github.com/mkody/twitch-emoticons

Hitting the FFZ and BTTV urls with my own Twitch ID with cURL that they have in their `utils/constants.js` shows that they still work. As long as the package isn't being used for emotes provided by Twitch then you don't need to have a ClientID/Secret.

I'd be happy to integrate it and submit a pull request later in the week as I have more time.

**Comment by Enubia** [comment]
> @Enubia I haven't had time to test it however this seems like it would do what you need it to do: https://github.com/mkody/twitch-emoticons
> 
> Hitting the FFZ and BTTV urls with my own Twitch ID with cURL that they have in their `utils/constants.js` shows that they still work. As long as the package isn't being used for emotes provided by Twitch then you don't need to have a ClientID/Secret.
> 
> I'd be happy to integrate it and submit a pull request later in the week as I have more time.

I'd be happy to review a PR from you with the additions to FFZ and BTTV.

**Comment by Enubia** [comment]
https://github.com/Enubia/ghost-chat/releases/tag/v2.0.0
