### ISSUE TITLE
Chat display is "nesting" messages

### ISSUE THREAD

**Issue by chocomallows** [Enubia/ghost-chat#319]
**Checklist before reporting**
- Is it really a bug or actually a feature request? Bug.
- Is there already another issue related to your problem? No.
- Do you have resources to reproduce it? Yes:
![image](https://user-images.githubusercontent.com/24209183/104106770-e9352880-52b7-11eb-8886-472386e00768.png)

**Describe the bug**
While testing the software and adjusting the settings to my needs, I noticed that after resizing the window to my desired size, the test-messages I was sending were not properly appearing. As opposed to a straight line down, they're forming a staircase.

**To Reproduce**
1. Adjust size to your needs
2. Start typing some test-messages
3. Observe

**Uncaught Exception Errors**
1. Navigate to ```%USERPROFILE%\AppData\Roaming\ghost-chat\logs```
2. Attach the main.log file to the issue. (This contains the whole stack trace of the error message)
=> Log file is empty.

**Expected behavior**
The chat messages appearing as a neat stack/tower. 
![image](https://user-images.githubusercontent.com/24209183/104106972-7f1d8300-52b9-11eb-9b88-98bf0ce61e33.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/24209183/104106812-50eb7380-52b8-11eb-87c6-3ea2e7954b61.png)

**Additional context**
I may very well have messed up certain settings without realising, I only today downloaded the software after all.

**Comment by chocomallows** [comment]
UPDATE:
It may also be related to the font size. I upped the font size dramatically and now it does show up as expected:
![image](https://user-images.githubusercontent.com/24209183/104107045-f0f5cc80-52b9-11eb-9701-1b8170feea8a.png)

Only problem of course is that this font size is not according to my needs, since it would also force me to make the chat window way larger than I would want.

**Comment by Enubia** [comment]
resolved with next release, issue occured on font sizes smaller than 9pt
