### ISSUE TITLE
Make it so that when one is scrolling the chat, new messages don't bring the chat list back to the top

### ISSUE THREAD

**Issue by Juansero29** [Enubia/ghost-chat#335]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when new messages don't let me read entirely or focus on longer messages of other users. 

**Describe the solution you'd like**
One should be able to pause the chat auto-scrolling.

**Describe alternatives you've considered**
There's no alternatives.

**Additional context**
This can happen when a longer message is sent and I want to read it but the other new messages don't allow me to.

**Comment by Enubia** [comment]
I've looked into this today before I was releasing the new version but couldn't come up with a proper solution for now due to the process of how the messages are rendered. I will keep this issue open tho since I realized that it's quite annoying sometimes.

**Comment by Enubia** [comment]
https://github.com/Enubia/ghost-chat/releases/tag/v2.0.0
