### ISSUE TITLE
Option to add the viewer count to the chat somewhere

### ISSUE THREAD

**Issue by Juansero29** [Enubia/ghost-chat#344]
**Is your feature request related to a problem? Please describe.**
If there are two vital informations for a small streamer those would be chat messages and viewer count. Viewer can't isn't available.
**Describe the solution you'd like**
An optional little label that allows to have the viewer count in the screen as well.

**Describe alternatives you've considered**
Not alternatives possible.

**Additional context**
It would be great to have the viewer count close to the chat when using ghost-chat. This would proof useful to know if someone new is watching to encourage the viewers to interact.

**Comment by rursi** [comment]
+

**Comment by Juansero29** [comment]
I don't think this should go to stale. It seems feasible?

**Comment by Juansero29** [comment]
Won't fix again? hum

**Comment by Enubia** [comment]
I've reviewed this issue today and without a client_id I can't really do anything to add the viewer count as this would need requests to the twitch API directly. If I'm going to create an app I will definitely include this request into a next release.

**Comment by Enubia** [comment]
closing this for now since I'm not going to create an official twitch app in the near future
