### ISSUE TITLE
Additional Mention Window

### ISSUE THREAD

**Issue by sp96296** [Enubia/ghost-chat#345]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Separate chat window option for mentions / highlighted messages, so you can easily see both normal chat and mentions. Perhaps specify a user to show mentions for, helping both streamers and viewers of a stream keep up in chaotic/busy chats.

**Describe alternatives you've considered**
N/A

**Additional context**
Would rather not scroll to find mentions/replies/etc

**Comment by Enubia** [comment]
this will be probably a bigger change but I will look into it once I've resolved the other issues that are open. Good point tho and nice idea.
