### ISSUE TITLE
Lock opening position and size

### ISSUE THREAD

**Issue by Glorithan** [Enubia/ghost-chat#356]
**Is your feature request related to a problem? Please describe.**

Whenever I open the program is always opens in the same place. The top left side of my main monitor.

**Describe the solution you'd like**

Is it possible to place it where I want it and lock it in place? So that when I close it and turn it back on it opens in the same size and position?

**Describe alternatives you've considered**

Moving it every time

**Additional context**

**Comment by Enubia** [comment]
this looks like a bug because it actually saves the position on which it was closed

can you please check if the data in ```%adddata%\Roaming\ghost-chat\config.json``` is changing when you move the window?

**Comment by Glorithan** [comment]
First off thanks for the quick response time!

I closed the program. Copied the content of config.json to a new notepad and closed it. I then reopened the program and moved it around and placed it on different monitors and different places/sizes.

Nothing ever changed. Below is what the contents are.

`{
	"dataCleared": true,
	"opacityLevel": "1",
	"showBorders": true,
	"clickThrough": false,
	"savedWindowState": {
		"posX": 1412,
		"posY": 1436,
		"sizeX": 805,
		"sizeY": 442
	},
	"fontStroke": false,
	"reverseChat": false,
	"chatColor": "white",
	"defaultChannel": "Glorithan",
	"timer": 0,
	"fontSize": "12",
	"channel": "Glorithan"
}`

**Comment by Glorithan** [comment]
I would also like to note here since we are talking about bugs, that even after removing and reinstalling the program, it still tells me that v1.3.3 is available even though I'm on that version.

https://i.imgur.com/ec345HF.png

**Comment by Enubia** [comment]
I assume this was a one time bug of some sort as the new releases are working fine from what I've seen so far and tested.
