### ISSUE TITLE
Channel Points redemptions

### ISSUE THREAD

**Issue by SP00K-E** [Enubia/ghost-chat#399]
**Is your feature request related to a problem? Please describe.**
Channel points/bits redeems don't seem to appear in the chat overlay.

**Describe the solution you'd like**
Overlay displaying channel points redeems.

**Describe alternatives you've considered**
Using my phone as a chat box until I can afford a second monitor.

**Comment by Enubia** [comment]
https://github.com/Enubia/ghost-chat/releases/tag/v2.0.0
