### ISSUE TITLE
Add a text-shadow option

### ISSUE THREAD

**Issue by rmorrise** [Enubia/ghost-chat#405]
**Is your feature request related to a problem? Please describe.**
Depending on which program I have open underneath, it can be hard to read the chat. I have to reposition the chat frequently or change the color to make it legible.

**Describe the solution you'd like**
It would be great to have an option to add a drop shadow on the text (CSS ```text-shadow```). I think it would really improve readability while still allowing me to see some of the stuff underneath the overlay.

**Describe alternatives you've considered**
Repositioning the window, changing the color or opacity, depending on which game I'm playing or whether I have my browser open.

**Additional context**
N/A

**Comment by Enubia** [comment]
![image](https://user-images.githubusercontent.com/44695100/164334446-7a753160-d252-449a-a219-de564b6fafe1.png)
this actually can be achieved by clicking this option here, I just noticed a little bug with the text-shadows which I've fixed now together with some other improvements in the next release
