### ISSUE TITLE
"window transparency" is actually opacity

### ISSUE THREAD

**Issue by rmorrise** [Enubia/ghost-chat#406]
**Is your feature request related to a problem? Please describe.**
The opacity setting in the Settings menu is incorrectly labeled as "window transparency". Window transparency is the inverse of opacity.

**Describe the solution you'd like**
Either rename the setting to Opacity, or invert the behavior by using  (100-(Window transparency)) when setting the opacity of the window. In other words, 100% transparency should be clear and 0% transparency should be opaque.

**Describe alternatives you've considered**
N/A

**Additional context**
right-click > Settings > General > Window transparency
background color is black, show borders=true

**Comment by Enubia** [comment]
hey, thanks for raising this!
I gladly accept a pr that addresses this issue :D

**Comment by Enubia** [comment]
fixed in https://github.com/Enubia/ghost-chat/releases/tag/v1.4.3
