### ISSUE TITLE
[Suggestion] Chat Text Fade overtime

### ISSUE THREAD

**Issue by CasualTerror** [Enubia/ghost-chat#408]
It would be great if the chat text faded after a period of time. As someone who doesn't have a very active chat or has a length of time between chat messages, messages that stay on the screen that is 5 or so minutes old can get in the way. Having the timer be something like 30sec or 1min to like 5min would be helpful.

**Comment by Enubia** [comment]
this is already possible on the settings page, there you can set a fadeout timer in seconds
