### ISSUE TITLE
Recently follower

### ISSUE THREAD

**Issue by missiah** [Enubia/ghost-chat#409]
Could you add a function to display recent followers? I know it would involve twitch API and login with twitch account but it would be a amazing addition for a one Monitor Streamer 🙏

**Comment by djfrailey** [comment]
As an alternative solution, StreamElements Bot has a module that will chat whenever someone Follows, Tips, Subscribes, Raids, Hosts, etc, etc. Turning that on in the meantime would give you the desired outcome.

**Comment by Enubia** [comment]
https://github.com/Enubia/ghost-chat/releases/tag/v2.0.0
