### ISSUE TITLE
VR transparency

### ISSUE THREAD

**Issue by lane-ftw** [Enubia/ghost-chat#410]
**Is your feature request related to a problem? Please describe.**
Kind of a niche use case. I use ghost chat for chat on my wrist when streaming in VR using OVR toolkit, as GC is borderless and doesn't have a chat box.

**Describe the solution you'd like**
Transparency of what's under my wrist while in VR rather than my desktop background.

**Describe alternatives you've considered**
I've just got it set to a black background. AFAIK nobody has done anything like this for a transparent window in VR.

**Additional context**
Good luck. This seems like a hell of a thing to implement.

**Comment by Enubia** [comment]
That's like totally out of scope of this project, but would of course be a nice addition.
Unfortunately, I don't own a VR headset and thus can't check that out.
I'll leave this issue open tho, maybe someone who's capable of testing this can send a PR :D

**Comment by lane-ftw** [comment]
Turns out LIV has this as a feature.

**Comment by lane-ftw** [comment]
Turns out LIV has this as a feature.
