### ISSUE TITLE
Disable Badges, Customize Capitalization

### ISSUE THREAD

**Issue by anapalkov** [Enubia/ghost-chat#412]
**Is your feature request related to a problem? Please describe.**
By default all usernames are transformed into lowercase. Would be great if this could be a toggleable option between uppercase and lower case. All badges are currently displayed and this can cause some clutter if a user has 3+ badges enabled. If this could be a toggleable feature as well, it might help some with clarity.

**Describe the solution you'd like**
The ability to disable badges (subscriber, prime gaming, etc) and capitalization StrEAMER vs 'streamer')

**Comment by Enubia** [comment]
https://github.com/Enubia/ghost-chat/releases/tag/v2.0.0
