### ISSUE TITLE
Always notified of "version is available" at start

### ISSUE THREAD

**Issue by anapalkov** [Enubia/ghost-chat#413]
**Describe the bug**
Even when on latest version (1.42), after starting the application, it says "Version is available!". I tried a clean install and this issue persists.

**To Reproduce**
Start the application
![bug2](https://user-images.githubusercontent.com/82188953/202602462-a7e25fe0-2ce2-4ff2-a705-bf03badd834f.png)

**Comment by Enubia** [comment]
seems like that something changed with githubs API, will be checked of course

**Comment by Enubia** [comment]
fixed in https://github.com/Enubia/ghost-chat/releases/tag/v1.4.3
