### ISSUE TITLE
Deleted messages

### ISSUE THREAD

**Issue by sloah** [Enubia/ghost-chat#416]
I would really appreciate an option to customize whether deleted messages are shown in the ghost chat box. It would be helpful if any messages my mods delete from my chat do not show up on my ghost chat, because they delete spoilers and hints for the game, but they still show up on ghost chat so I see the spoilers anyways. 

A toggle button in the settings for whether deleted messages are shown in the chat box would be an ideal solution. 

I don't know whether a message can be deleted once it is shown in the box, if it can not, maybe an option to have a delay on chat showing up in the chat box, so that mods have time to delete the message before it even spawns in the chat box.

**Comment by Enubia** [comment]
https://github.com/Enubia/ghost-chat/releases/tag/v2.0.0
