### ISSUE TITLE
MacOS Support 🙏🏼 

### ISSUE THREAD

**Issue by alandooz** [Enubia/ghost-chat#418]
Jus that. This is exactly what I'm looking for, but needed on MacOS.

**Comment by alandooz** [comment]
Also, I leave this just in case it's good for something: https://github.com/electron/electron/issues/10078

**Comment by Enubia** [comment]
Mac support will be added back in v2

**Comment by Enubia** [comment]
@alandooz https://github.com/Enubia/ghost-chat/releases/tag/v2.0.0-beta.3 the latest beta release should have a working mac release now. In case you want to test it I'd recommend to report any issues with it in the [Discord](https://discord.gg/UVMX32dDcy)
