### ISSUE TITLE
overlay not showing in baldurs gate 3 

### ISSUE THREAD

**Issue by AtlasCain** [Enubia/ghost-chat#597]
when I launch the game I can no longer see the overlay I made sure im using fake fullscreen mode and I ran as admin no luck and the powertoys always on top trick does not work either.

**Comment by Enubia** [comment]
Could you provide me with the logs, please?
They can be found on the tray menu
![image](https://github.com/Enubia/ghost-chat/assets/44695100/56b199c2-e0b5-4d72-a6b2-ab094f29915b)

Attach the last to logs if possible

**Comment by AtlasCain** [comment]
[app-6-6-2023.log](https://github.com/Enubia/ghost-chat/files/11967051/app-6-6-2023.log)
there are the logs

**Comment by Enubia** [comment]
Ok so there's no crash or anything in there. Are you using any other programm in combination with baldurs gate and ghost chat?

What are your video settings in game?

**Comment by AtlasCain** [comment]
the game is being run through steam I have the resolution at 1920x1080 with v synch on and I have it set to Fake Fullscreen mode which is the equivalent of borderless window for the game.

**Comment by AtlasCain** [comment]
also its running on vulkan

**Comment by AtlasCain** [comment]
dang well its still in early acess so hopefully the 1.0 release will fix it thanks for your help.
