### ISSUE TITLE
[Request] add vue router

### ISSUE THREAD

**Issue by Enubia** [Enubia/ghost-chat#676]
We are at a point where we should consider using https://router.vuejs.org/ since the logic for page switching will only get more complicated. With this, we would not need this big switch statement anymore and make things easier to navigate in the future

```ts
const showView = <T = 'chat' | 'start' | 'settings' | 'externalSource',>(view: T) => {
	switch (view) {
		case 'chat':
			showChat.value = true;
			showStart.value = false;
			showSettings.value = false;
			showExternalSource.value = false;
			showMenuBar.value = true;
			break;

		case 'start':
			...
	}
}
```

**Comment by AmithBino** [comment]
Can i try this?

**Comment by Enubia** [comment]
> Can i try this?

sure thing, shouldn't be too hard to add

**Comment by AmithBino** [comment]
Sorry i dont understand it.

**Comment by Enubia** [comment]
> Sorry i dont understand it. We need to make a router.js file which routes through the website ryt?

yes I was just explaining where the routing should happen once the router file is created and all the routes are mounted

**Comment by AmithBino** [comment]
Yeah okay let me try
