### ISSUE TITLE
[Request] global hotkey assignment

### ISSUE THREAD

**Issue by Enubia** [Enubia/ghost-chat#762]
add a global hotkey assignment to switch between vanish mode and default

should be something that isn't commonly used and needs to be editable

https://www.electronjs.org/docs/latest/api/global-shortcut

**Comment by dsimonow** [comment]
gonna have a look at this.

**Comment by Enubia** [comment]
@dsimonow whats your progress so far? I wanted to release a new version in the next couple of days since electron was upgraded to v28

**Comment by dsimonow** [comment]
I am at the finish line. 
Got the shortcut working still need to refactor the vanish ipc, since now it can be called at any time. 
Also some general cleaning up, since it was first time for me using electron. 
Probably a few more days, since the past days were busy for me.

**Comment by Enubia** [comment]
resolved in https://github.com/Enubia/ghost-chat/commit/85a93b31bfa29de3458aae9df39d7ed07f5e7d23
