### ISSUE TITLE
[Request] 7TV emotes

### ISSUE THREAD

**Issue by poheSAMP** [Enubia/ghost-chat#763]
Currently it seems like the only emotes that show are Twitch emotes, would be nice to have 7TV (and BetterTTV and FFZ).

**Comment by Enubia** [comment]
unfortunately, this is a limitation of https://nightdev.com/kapchat

there are already requests to add 7TV but the nightdev guys said they won't add them

in your case I'd recommend loading https://www.giambaj.it/twitch/jchat/ via the external source option, jchat has 7TV and FFZ built in

**Comment by Enubia** [comment]
detailed instructions can be found in the discord faq channel in the section **Loading External Sources**
