### ISSUE TITLE
[Request] add in app changelog

### ISSUE THREAD

**Issue by Enubia** [Enubia/ghost-chat#774]
We should add a changelog to show new additions after updates

It Can be part of the main menu.

Maybe we can somehow automate the update of it

**Comment by Enubia** [comment]
@dsimonow

Do you think you could take this? I'd like to have it for the next release since most of the users don't look at the GitHub changelog after an update happens. And with the new hotkey toggle, it would make sense to show them that they now have the option to use that

**Comment by dsimonow** [comment]
yeah I can have a look

**Comment by Enubia** [comment]
@dsimonow I'm working on this myself right now since I want it to be somewhat readable for non tech users, thanks for looking into it tho
