### ISSUE TITLE
[Bug] Vanish Keybind does not work

### ISSUE THREAD

**Issue by Sammymouse** [Enubia/ghost-chat#780]
Clicking in the box where it says 'No keybind set' and pushing buttons does not work.

Manual editing of the config.json also does not work. It only actives the menu in Ghost-chat with the Start, settings, etc options.

Only a minor bug that I should be noted. 

It won't effect my personal use, because I have been a major fan of Ghost-chat since nearly two years ago now! <3

Thank you Enubia for the hard work.

**Comment by Enubia** [comment]
What Keybind are you trying to use? It requires at least one modifier key (ctrl, alt order shift)

**Comment by Enubia** [comment]
in case you used a single function key, the next release will include the option to use function keys without modifiers

**Comment by Enubia** [comment]
closing as there's no answer right now
