### ISSUE TITLE
[Bug] chat messages don`t fade out

### ISSUE THREAD

**Issue by AdvocatusDei** [Enubia/ghost-chat#788]
Hey everbody,

i told ghost-chat in the settings to fade out new messages after 20 sekonds, bot they stay, the whole chat stays visible the whole time. Is there a easy fix for that. And the font is very little on a 4k display, how to change the font size i dont find it in the settings.

**Comment by Enubia** [comment]
can you provide me a screenshot of your "Kapchat" settings?

additionally, in the tray icon menu, there's a miscellaneous section with a debug information option, please also paste this into your answer
