### ISSUE TITLE
Latest Ghost-Chat EXE (1.1.5) always says there's a newer version

### ISSUE THREAD

**Issue by rmorrise** [Enubia/ghost-chat#83]
**Checklist before reporting**
[x] Is it really a bug or actually a feature request?
[x] Is there already another issue related to your problem?
[x] Do you have resources to reproduce it?

**Describe the bug**
In GitHub releases, I downloaded "Ghost-Chat-1.1.5.exe" from the latest release, which is listed as v1.2.0.

Whenever I run the app, it checks for a new version, and says "Version v1.2.0 is available!" but the latest version on the GitHub release page is still the same.

I'm assuming this is somehow caused by or related to the installer issue mentioned in the release notes.

**To Reproduce**
1. Download Ghost-Chat-1.1.5.exe from the release page
2. Launch the app and check for updates

**Uncaught Exception Errors**
N/A

**Expected behavior**
Since this is the latest version at the time of this posting, I shouldn't be getting a message that an update is available.

**Screenshots**
![image](https://user-images.githubusercontent.com/8999824/88497002-edc98700-cf8c-11ea-9f8a-40cb5bd80f4a.png)

**Additional context**
WIndows 10, x64

**Comment by Enubia** [comment]
Seems like I accidentally created the build with the wrong version number, shouldn't have an impact on the app tho. I will fix this issue today with a new build so that the versioning is corrected.

**Comment by Enubia** [comment]
fixed with 2c71efc
