### ISSUE TITLE
road to v3

### ISSUE THREAD

**Issue by Enubia** [Enubia/ghost-chat#844]
Since there's more and more demand for YouTube to be integrated and some additional things for Twitch, I decided to go with custom chat integrations again.

This includes:

~~a new chat integration for YouTube~~
~~a custom chat integration for Twitch~~
~~mixing both of them into a single feed~~
~~multi-window support~~ will be added in a later release
- [x] using jchat instead of kapchat for twitch
- [x] integrate kick.com
- [ ] integrate tiktok
- [ ] integrate youtube (will be hidden behind and experimental flag, reasons why will be stated in the release)
- [x] a complete redesign of the UI

I don't have a release date yet, but I started working on it and will let you know the progress.
Let me know in Discord or the comments below if you have any suggestions or ideas.

**Comment by sugoides** [comment]
Ghost chat does not show in VALORANT Fullscreen

**Comment by Enubia** [comment]
> Ghost chat does not show in VALORANT Fullscreen

that's because fullscreen is not supported

**Comment by ChromesDuzez** [comment]
a ui suggestion that I'd love to see would be, the built-option to have a very an adjustable transparenty backround in vanish mode so that the chat is legible even if the colors behind it would normally make it difficult?
