### ISSUE TITLE
[Help] the title of help you want

### ISSUE THREAD

**Issue by Jmitro980** [Enubia/ghost-chat#862]
Hello names MK i am having issues with your app acting like it cant be put up on screen it opens it but nothing appears and when i have the course over the icon it shows the app open but wont let me inter act with it.

**Comment by Enubia** [comment]
does this happen all the time or only the first time after the installation?

**Comment by Jmitro980** [comment]
Its inconsistent really sometimes it just works others it doesnt im not
sure why i have just downloaded and reinstalled it to test but still fid
the same thing

**Comment by Enubia** [comment]
Can you try the following, please 

- delete C:\Users\<your user name>\AppData\Roaming\ghost-chat
- uninstall ghost chat, if you haven't changed the default directory it should be in C:\Users\<your user name>\AppData\Local\Programs\Ghost-Chat
- install ghost chat again

**Comment by Enubia** [comment]
Should be fixed with https://github.com/Enubia/ghost-chat/releases/tag/v2.9.0
