### ISSUE TITLE
[Help] Orientation in the app is different

### ISSUE THREAD

**Issue by verihiiri** [Enubia/ghost-chat#922]
I had just gotten this app and I absolutely love it. One of the things that has changed and I cannot figure out how to change it is that the text in chat used to be at the top near the hamburger menu and then as people type in chat, it fills down, but now it appears on the bottom and then "scrolls" up. Is there a way to change it back as it was in 2.9.0 version?

**Comment by Enubia** [comment]
this was introduced when I switched the chat overlay from Kapchat to Jchat.
Jchat does not support it as far as I know but I can maybe try to figure something out that the direction can be reversed

**Comment by verihiiri** [comment]
Thank you for your prompt response. I love this app and it's so inventive! Keep up the good work!

**Comment by Katwyld** [comment]
Add one for wanting the text back to how it was. But I can understand something messing with how it is, not that you changed it intentionally. Thank you for looking at this! :)

**Comment by Enubia** [comment]
resolved with https://github.com/Enubia/ghost-chat/releases/tag/v3.2.0
