### ISSUE TITLE
[Help] putting background on chat text

### ISSUE THREAD

**Issue by Di-Lunis** [Enubia/ghost-chat#932]
I've been playing around on the settings since the update. my chat text used to have a background, making it easier to read. is there a way to put that back on with this new update? the chat is hard to read now

**Comment by Enubia** [comment]
I assume you used some custom css?

Can you post that here so I can take a look at it?

**Comment by Di-Lunis** [comment]
I did not use a custom css, this was just a setting i think? like before the update my text had a background and after the update it doesn't anymore

**Comment by Enubia** [comment]
you can apply some text shadow and font stroke through the settings

![image](https://github.com/Enubia/ghost-chat/assets/44695100/e30222e2-9308-4873-8852-e94441133a4a)

**Comment by Di-Lunis** [comment]
I have tried to change those settings, but nothing happens at first then the text would just be black and completely unreadable

**Comment by Enubia** [comment]
![image](https://github.com/Enubia/ghost-chat/assets/44695100/8036931c-2872-4701-a06b-3ebc13a18ed6)
can you click on copy debug info and paste that here?

I'd like to check your config

**Comment by Di-Lunis** [comment]
I  do not see that option

**Comment by Di-Lunis** [comment]
i had to redownload it to update but I still don't see that option

**Comment by Enubia** [comment]
this option is available through the tray icon menu
