### ISSUE TITLE
[Bug] the title of the bug report

### ISSUE THREAD

**Issue by lockedoutside** [Enubia/ghost-chat#966]
#### Describe the bug

I was really enjoying the ghost chat app on my pc. I was able to easily read it while playing games on twitch.

The issues started with the most recent update. 

I had to reset many of the settings when I started streaming, then I noticed that I can no longer add and opaque background behind the text during vanish mode, which makes it very hard to easily read while playing. 

Please, I really enjoyed using this, and have been recommending it to others. 

I really hope this can be corrected. 

Thank you.

**Comment by Enubia** [comment]
should be fixed with the latest release https://github.com/Enubia/ghost-chat/releases/tag/v3.2.0
