### ISSUE TITLE
Window permanently off screen

### ISSUE THREAD

**Issue by icavero101** [Enubia/ghost-chat#993]
My window is bugged and off screen somehow.  I have reinstalled the program many times and it is still outside my monitor view.  I tried to use the cascade command and it did not bring the window over.  Similarly I tried to shift+right click on the taskbar icon to manually move it, but the menu to select move does not even show up.  I really like this program but I am unsure how to fix this issue. Any Help would be greatly appreciated.

**Comment by CodeCureoffical** [comment]
I am the founder of CodeCure.codes I am willing to look over this code for free. Contact me at projects@codecure.codes with specifics and code I’ll have my team get on it as soon as I get your email.

**Comment by Enubia** [comment]
you can reset your config via the tray icon menu, this resets the window position to the center of the screen again

**Comment by Trisito98** [comment]
I've tried resetting the config, and it remains off screen? any other suggestion?

**Comment by Enubia** [comment]
can you please try deleting ghost-chat and installing the latest version of it?

**Comment by Trisito98** [comment]
I've just tried that, same issue i'm afraid still off screen

**Comment by Enubia** [comment]
mind trying these steps from the discord FAQ?

---

A possible solution to this is using a tool like Revo <https://www.revouninstaller.com/products/revo-uninstaller-free/>
This can get rid of all files created by Ghost Chat

- install it again
- run revo
- select ghost chat
- uninstall
- click on "Scan"
- click "Select All" -> "Delete", repeat this process until there are no more files listed
    - **NOTE**: this will also delete your config file
- install Ghost Chat again

**Comment by Trisito98** [comment]
this has fixed the problem now, thanks so much
